services:
  app:
    build: .
    image: impetrosys/root_apis:v1_27May
    container_name: root_apis
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8001:8001"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: