// module.exports = {
//   // ===== USER MODULE (USR) =====
//   USER_CREATED: 'USR_201',
//   USER_UPDATED: 'USR_202',
//   USER_LIST_FETCHED: 'USR_200',

//   AUTH_TOKEN_INVALID: 'AUTH_401',
//   USER_NOT_FOUND: 'USR_404',
//   USER_EMAIL_EXISTS: 'USR_409',
//   USER_INVALID_ROLE: 'USR_400',
//   USER_CREATE_FAILED: 'USR_500',
//   USER_UPDATE_FAILED: 'USR_501',
//   USER_LIST_FAILED: 'USR_502',

//   // ===== PASSWORD (PWD) =====
//   PASSWORD_TOO_WEAK: 'PWD_400',
//   PASSWORD_REQUIRED: 'PWD_401',
//   PASSWORD_CURRENT_INVALID: 'PWD_403',
//   PASSWORD_RESET_FAILED: 'PWD_500',
//   PASSWORD_CHANGE_FAILED: 'PWD_501',

//   // ===== VALIDATION (VAL) =====
//   VALIDATION_NAME_REQUIRED: 'VAL_001',
//   VALIDATION_EMAIL_REQUIRED: 'VAL_002',
//   VALIDATION_PASSWORD_REQUIRED: 'VAL_003',
//   VALIDATION_ROLE_REQUIRED: 'VAL_004',
//   VALIDATION_PHONE_CODE_REQUIRED: 'VAL_005',
//   VALIDATION_PHONE_REQUIRED: 'VAL_006',
//   VALIDATION_INVALID_EMAIL: 'VAL_007',
//   VALIDATION_INVALID_PHONE: 'VAL_008',
//   VALIDATION_INVALID_PASSWORD: 'VAL_009',


//   // // Role module error codes
//   // ROLE_NAME_REQUIRED: 'ROL_400',
//   // ROLE_ALREADY_EXISTS: 'ROL_400',
//   // ROLE_CREATE_FAILED: 'ROL_500',
//   // ROLE_LIST_FAILED: 'ROL_500',
//   // ROLE_NOT_FOUND: 'ROL_404',
//   // ROLE_UPDATE_FAILED: 'ROL_500',
//   // ROLE_STATUS_UPDATE_FAILED: 'ROL_500',
//   // PERMISSIONS_ASSIGN_FAILED: 'ROL_500',
//   // ROLE_SUPER_ADMIN_PROTECTED: 'ROL_403',

//   // // Validation errors
//   // MODULES_ARRAY_REQUIRED: 'ROL_400',
//   // MODULE_KEY_REQUIRED: 'ROL_400',
//   // INVALID_MODULE_KEY: 'ROL_400',
//   // ACTIONS_ARRAY_REQUIRED: 'ROL_400',
//   // ACTION_KEY_REQUIRED: 'ROL_400',
//   // INVALID_ACTION_KEY: 'ROL_400'

//   ROLE_NAME_REQUIRED: 'ROL_400',
//   ROLE_EXISTS: 'ROL_400',
//   ROLE_CREATED: 'ROL_201',
//   ROLE_CREATE_FAILED: 'ROL_500',
//   ROLE_LIST_FETCHED: 'ROL_200',
//   ROLE_LIST_FAILED: 'ROL_500',
//   ROLE_NOT_FOUND: 'ROL_404',
//   ROLE_UPDATED: 'ROL_200',
//   ROLE_UPDATE_FAILED: 'ROL_500',
//   ROLE_STATUS_REQUIRED: 'ROL_400',
//   ROLE_STATUS_UPDATED: 'ROL_200',
//   ROLE_STATUS_UPDATE_FAILED: 'ROL_500',
//   MODULES_ARRAY_REQUIRED: 'ROL_400',
//   MODULE_KEY_REQUIRED: 'ROL_400',
//   INVALID_MODULE_KEY: 'ROL_400',
//   ACTIONS_ARRAY_REQUIRED: 'ROL_400',
//   ACTION_KEY_REQUIRED: 'ROL_400',
//   INVALID_ACTION_KEY: 'ROL_400',
//   CANNOT_MODIFY_SUPER_ADMIN: 'ROL_403',
//   PERMISSIONS_UPDATED: 'ROL_200',
//   PERMISSIONS_ASSIGN_FAILED: 'ROL_500',
//   PLAN_ALREADY_EXISTS: 'PLN_409',
// };



module.exports = {
  /* ======================================================
     AUTH MODULE (AUTH)
  ====================================================== */
  AUTH_LOGIN_SUCCESS: "AUTH_200",
  AUTH_LOGOUT_SUCCESS: "AUTH_200",
  AUTH_REGISTER_SUCCESS: "AUTH_201",

  AUTH_TOKEN_INVALID: "AUTH_401",
  AUTH_SESSION_EXPIRED: "AUTH_401",
  AUTH_INVALID_CREDENTIALS: "AUTH_401",
  AUTH_UNAUTHORIZED: "AUTH_401",

  AUTH_ACCESS_DENIED: "AUTH_403",
  AUTH_ACCOUNT_BLOCKED: "AUTH_403",

  AUTH_TOO_MANY_REQUESTS: "AUTH_429",

  AUTH_LOGIN_FAILED: "AUTH_500",
  AUTH_LOGOUT_FAILED: "AUTH_500",
  AUTH_REGISTER_FAILED: "AUTH_500",

  /* ======================================================
     USER MODULE (USR)
  ====================================================== */
  USER_CREATED: "USR_201",
  USER_UPDATED: "USR_200",
  USER_DELETED: "USR_200",
  USER_FETCHED: "USR_200",
  USER_LIST_FETCHED: "USR_200",

  USER_NOT_FOUND: "USR_404",
  USER_EMAIL_EXISTS: "USR_409",
  USER_PHONE_EXISTS: "USR_409",

  USER_INVALID_ROLE: "USR_400",
  USER_STATUS_REQUIRED: "USR_400",
  USER_INVALID_DATA: "USR_400",

  USER_CREATE_FAILED: "USR_500",
  USER_UPDATE_FAILED: "USR_500",
  USER_DELETE_FAILED: "USR_500",
  USER_FETCH_FAILED: "USR_500",
  USER_LIST_FAILED: "USR_500",

  /* ======================================================
     PASSWORD MODULE (PWD)
  ====================================================== */
  PASSWORD_REQUIRED: "PWD_400",
  PASSWORD_TOO_WEAK: "PWD_400",
  PASSWORD_CONFIRM_MISMATCH: "PWD_400",

  PASSWORD_CURRENT_INVALID: "PWD_401",

  PASSWORD_RESET_SUCCESS: "PWD_200",
  PASSWORD_CHANGED_SUCCESS: "PWD_200",

  PASSWORD_RESET_FAILED: "PWD_500",
  PASSWORD_CHANGE_FAILED: "PWD_500",

  /* ======================================================
     VALIDATION MODULE (VAL)
  ====================================================== */
  VALIDATION_ERROR: "VAL_400",

  VALIDATION_NAME_REQUIRED: "VAL_001",
  VALIDATION_EMAIL_REQUIRED: "VAL_002",
  VALIDATION_PASSWORD_REQUIRED: "VAL_003",
  VALIDATION_ROLE_REQUIRED: "VAL_004",
  VALIDATION_PHONE_CODE_REQUIRED: "VAL_005",
  VALIDATION_PHONE_REQUIRED: "VAL_006",

  VALIDATION_INVALID_EMAIL: "VAL_007",
  VALIDATION_INVALID_PHONE: "VAL_008",
  VALIDATION_INVALID_PASSWORD: "VAL_009",

  VALIDATION_INVALID_ID: "VAL_010",
  VALIDATION_INVALID_STATUS: "VAL_011",

  /* ======================================================
     ROLE MODULE (ROL)
  ====================================================== */
  ROLE_CREATED: "ROL_201",
  ROLE_UPDATED: "ROL_200",
  ROLE_DELETED: "ROL_200",
  ROLE_FETCHED: "ROL_200",
  ROLE_LIST_FETCHED: "ROL_200",
  ROLE_STATUS_UPDATED: "ROL_200",
  PERMISSIONS_UPDATED: "ROL_200",

  ROLE_NAME_REQUIRED: "ROL_400",
  ROLE_STATUS_REQUIRED: "ROL_400",
  ROLE_EXISTS: "ROL_409",

  MODULES_ARRAY_REQUIRED: "ROL_400",
  MODULE_KEY_REQUIRED: "ROL_400",
  INVALID_MODULE_KEY: "ROL_400",

  ACTIONS_ARRAY_REQUIRED: "ROL_400",
  ACTION_KEY_REQUIRED: "ROL_400",
  INVALID_ACTION_KEY: "ROL_400",

  ROLE_NOT_FOUND: "ROL_404",

  CANNOT_MODIFY_SUPER_ADMIN: "ROL_403",

  ROLE_CREATE_FAILED: "ROL_500",
  ROLE_UPDATE_FAILED: "ROL_500",
  ROLE_DELETE_FAILED: "ROL_500",
  ROLE_LIST_FAILED: "ROL_500",
  ROLE_STATUS_UPDATE_FAILED: "ROL_500",
  PERMISSIONS_ASSIGN_FAILED: "ROL_500",

  /* ======================================================
     SUBSCRIPTION / PLAN MODULE (PLN)
  ====================================================== */
  PLAN_CREATED: "PLN_201",
  PLAN_UPDATED: "PLN_200",
  PLAN_DELETED: "PLN_200",
  PLAN_FETCHED: "PLN_200",
  PLAN_LIST_FETCHED: "PLN_200",

  PLAN_ALREADY_EXISTS: "PLN_409",
  PLAN_NOT_FOUND: "PLN_404",

  PLAN_INVALID_PRICE: "PLN_400",
  PLAN_INVALID_DURATION: "PLN_400",
  PLAN_STATUS_REQUIRED: "PLN_400",

  PLAN_ASSIGNED_SUCCESS: "PLN_200",
  PLAN_EXPIRED: "PLN_403",
  PLAN_INACTIVE: "PLN_403",

  PLAN_CREATE_FAILED: "PLN_500",
  PLAN_UPDATE_FAILED: "PLN_500",
  PLAN_DELETE_FAILED: "PLN_500",
  PLAN_FETCH_FAILED: "PLN_500",
  PLAN_LIST_FAILED: "PLN_500",
  PLAN_ASSIGN_FAILED: "PLN_500",

  SUBSCRIPTION_CREATED: "SUB_201",
  SUBSCRIPTION_UPDATED: "SUB_200",
  SUBSCRIPTION_CANCELLED: "SUB_200",
  SUBSCRIPTION_FETCHED: "SUB_200",

  SUBSCRIPTION_NOT_FOUND: "SUB_404",
  SUBSCRIPTION_ALREADY_ACTIVE: "SUB_409",

  SUBSCRIPTION_PAYMENT_FAILED: "SUB_402",
  SUBSCRIPTION_EXPIRED: "SUB_403",

  SUBSCRIPTION_CREATE_FAILED: "SUB_500",
  SUBSCRIPTION_UPDATE_FAILED: "SUB_500",

  /* ======================================================
     KYB MODULE (KYB)
  ====================================================== */
  KYB_SUBMITTED: "KYB_201",
  KYB_UPDATED: "KYB_200",
  KYB_FETCHED: "KYB_200",
  KYB_LIST_FETCHED: "KYB_200",

  KYB_PENDING: "KYB_202",
  KYB_APPROVED: "KYB_200",
  KYB_REJECTED: "KYB_403",

  KYB_ALREADY_SUBMITTED: "KYB_409",
  KYB_NOT_FOUND: "KYB_404",

  KYB_DOCUMENT_REQUIRED: "KYB_400",
  KYB_INVALID_DOCUMENT: "KYB_400",
  KYB_STATUS_REQUIRED: "KYB_400",

  KYB_VERIFICATION_FAILED: "KYB_500",
  KYB_SUBMISSION_FAILED: "KYB_500",
  KYB_UPDATE_FAILED: "KYB_500",

  /* ======================================================
     COMMON / GLOBAL
  ====================================================== */
  SUCCESS: "COM_200",
  CREATED: "COM_201",

  BAD_REQUEST: "COM_400",
  UNAUTHORIZED: "COM_401",
  FORBIDDEN: "COM_403",
  NOT_FOUND: "COM_404",
  CONFLICT: "COM_409",
  TOO_MANY_REQUESTS: "COM_429",

  INTERNAL_SERVER_ERROR: "COM_500",
};