module.exports = {
  // ===== USER MODULE (USR) =====
  USER_CREATED: 'USR_201',
  USER_UPDATED: 'USR_202',
  USER_LIST_FETCHED: 'USR_200',

  USER_NOT_FOUND: 'USR_404',
  USER_EMAIL_EXISTS: 'USR_409',
  USER_INVALID_ROLE: 'USR_400',
  USER_CREATE_FAILED: 'USR_500',
  USER_UPDATE_FAILED: 'USR_501',
  USER_LIST_FAILED: 'USR_502',

  // ===== PASSWORD (PWD) =====
  PASSWORD_TOO_WEAK: 'PWD_400',
  PASSWORD_REQUIRED: 'PWD_401',
  PASSWORD_CURRENT_INVALID: 'PWD_403',
  PASSWORD_RESET_FAILED: 'PWD_500',
  PASSWORD_CHANGE_FAILED: 'PWD_501',

  // ===== VALIDATION (VAL) =====
  VALIDATION_NAME_REQUIRED: 'VAL_001',
  VALIDATION_EMAIL_REQUIRED: 'VAL_002',
  VALIDATION_PASSWORD_REQUIRED: 'VAL_003',
  VALIDATION_ROLE_REQUIRED: 'VAL_004',
  VALIDATION_PHONE_CODE_REQUIRED: 'VAL_005',
  VALIDATION_PHONE_REQUIRED: 'VAL_006',
  VALIDATION_INVALID_EMAIL: 'VAL_007',
  VALIDATION_INVALID_PHONE: 'VAL_008',
  VALIDATION_INVALID_PASSWORD: 'VAL_009',


  // // Role module error codes
  // ROLE_NAME_REQUIRED: 'ROL_400',
  // ROLE_ALREADY_EXISTS: 'ROL_400',
  // ROLE_CREATE_FAILED: 'ROL_500',
  // ROLE_LIST_FAILED: 'ROL_500',
  // ROLE_NOT_FOUND: 'ROL_404',
  // ROLE_UPDATE_FAILED: 'ROL_500',
  // ROLE_STATUS_UPDATE_FAILED: 'ROL_500',
  // PERMISSIONS_ASSIGN_FAILED: 'ROL_500',
  // ROLE_SUPER_ADMIN_PROTECTED: 'ROL_403',

  // // Validation errors
  // MODULES_ARRAY_REQUIRED: 'ROL_400',
  // MODULE_KEY_REQUIRED: 'ROL_400',
  // INVALID_MODULE_KEY: 'ROL_400',
  // ACTIONS_ARRAY_REQUIRED: 'ROL_400',
  // ACTION_KEY_REQUIRED: 'ROL_400',
  // INVALID_ACTION_KEY: 'ROL_400'

  ROLE_NAME_REQUIRED: 'ROL_400',
  ROLE_EXISTS: 'ROL_400',
  ROLE_CREATED: 'ROL_201',
  ROLE_CREATE_FAILED: 'ROL_500',
  ROLE_LIST_FETCHED: 'ROL_200',
  ROLE_LIST_FAILED: 'ROL_500',
  ROLE_NOT_FOUND: 'ROL_404',
  ROLE_UPDATED: 'ROL_200',
  ROLE_UPDATE_FAILED: 'ROL_500',
  ROLE_STATUS_REQUIRED: 'ROL_400',
  ROLE_STATUS_UPDATED: 'ROL_200',
  ROLE_STATUS_UPDATE_FAILED: 'ROL_500',
  MODULES_ARRAY_REQUIRED: 'ROL_400',
  MODULE_KEY_REQUIRED: 'ROL_400',
  INVALID_MODULE_KEY: 'ROL_400',
  ACTIONS_ARRAY_REQUIRED: 'ROL_400',
  ACTION_KEY_REQUIRED: 'ROL_400',
  INVALID_ACTION_KEY: 'ROL_400',
  CANNOT_MODIFY_SUPER_ADMIN: 'ROL_403',
  PERMISSIONS_UPDATED: 'ROL_200',
  PERMISSIONS_ASSIGN_FAILED: 'ROL_500'
};

