/**
 * @file Message Keys
 * @description Centralized message key constants for authentication,
 *              users, modules, roles, actions, validation, and system errors.
 *              Used for i18n + standardized API responses.
 */

module.exports = {

  // ========================================
  // 🔐 AUTHENTICATION
  // ========================================
  AUTH_LOGIN_SUCCESS: 'AUTH.LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH.LOGIN_FAILED',

  AUTH_INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',

  AUTH_TOKEN_MISSING: 'AUTH.TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH.TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH.TOKEN_EXPIRED',

  AUTH_ACCOUNT_INACTIVE: 'AUTH.ACCOUNT_INACTIVE',
  AUTH_ACCOUNT_LOCKED: 'AUTH.ACCOUNT_LOCKED',

  AUTH_LOGOUT_SUCCESS: 'AUTH.LOGOUT_SUCCESS',
  AUTH_LOGOUT_ALL_SUCCESS: 'AUTH.LOGOUT_ALL_SUCCESS',


  // ========================================
  // 🔑 PASSWORD & SECURITY
  // ========================================
  PASSWORD_TOO_WEAK: 'PASSWORD.TOO_WEAK',
  PASSWORD_REQUIRED: 'PASSWORD.REQUIRED',
  PASSWORD_CURRENT_INVALID: 'PASSWORD.CURRENT_INVALID',
  PASSWORD_RESET_FAILED: 'PASSWORD.RESET_FAILED',
  PASSWORD_CHANGE_FAILED: 'PASSWORD.CHANGE_FAILED',


  // ========================================
  // ✅ VALIDATION
  // ========================================
  VALIDATION_NAME_REQUIRED: 'VALIDATION.NAME_REQUIRED',
  VALIDATION_EMAIL_REQUIRED: 'VALIDATION.EMAIL_REQUIRED',
  VALIDATION_PASSWORD_REQUIRED: 'VALIDATION.PASSWORD_REQUIRED',
  VALIDATION_ROLE_REQUIRED: 'VALIDATION.ROLE_REQUIRED',

  VALIDATION_PHONE_CODE_REQUIRED: 'VALIDATION.PHONE_CODE_REQUIRED',
  VALIDATION_PHONE_REQUIRED: 'VALIDATION.PHONE_REQUIRED',

  VALIDATION_INVALID_EMAIL: 'VALIDATION.INVALID_EMAIL',
  VALIDATION_INVALID_PHONE: 'VALIDATION.INVALID_PHONE',
  VALIDATION_INVALID_PASSWORD: 'VALIDATION.INVALID_PASSWORD',

   // ========================================
  // 👤 USER PROFILE & ACCOUNT
  // ========================================
  USER_PROFILE_FETCHED: 'USER.PROFILE_FETCHED',
  USER_NOT_FOUND: 'USER.NOT_FOUND',

  USER_CREATED: 'USER.CREATED',
  USER_UPDATED: 'USER.UPDATED',
  USER_LIST_FETCHED: 'USER.LIST_FETCHED',

  USER_PASSWORD_RESET: 'USER.PASSWORD_RESET',
  USER_PASSWORD_CHANGED: 'USER.PASSWORD_CHANGED',

  USER_EMAIL_EXISTS: 'USER.EMAIL_EXISTS',
  USER_INVALID_ROLE: 'USER.INVALID_ROLE',

  USER_CREATE_FAILED: 'USER.CREATE_FAILED',
  USER_UPDATE_FAILED: 'USER.UPDATE_FAILED',
  USER_LIST_FAILED: 'USER.LIST_FAILED',


  // ========================================
  // 📦 MODULE MANAGEMENT
  // ========================================
  MODULE_KEY_REQUIRED: 'MODULE.KEY_REQUIRED',
  MODULE_EXISTS: 'MODULE.EXISTS',
  MODULE_CREATED: 'MODULE.CREATED',
  MODULE_CREATE_FAILED: 'MODULE.CREATE_FAILED',

  MODULE_LIST_FETCHED: 'MODULE.LIST_FETCHED',
  MODULE_LIST_FAILED: 'MODULE.LIST_FAILED',

  MODULE_NOT_FOUND: 'MODULE.NOT_FOUND',
  MODULE_FETCHED: 'MODULE.FETCHED',

  MODULE_UPDATED: 'MODULE.UPDATED',
  MODULE_UPDATE_FAILED: 'MODULE.UPDATE_FAILED',

  MODULE_DELETED: 'MODULE.DELETED',
  MODULE_DELETE_FAILED: 'MODULE.DELETE_FAILED',

  MODULE_STATUS_UPDATED: 'MODULE.STATUS_UPDATED',
  MODULE_STATUS_UPDATE_FAILED: 'MODULE.STATUS_UPDATE_FAILED',

  MODULE_INACTIVE: 'MODULE.INACTIVE',
  NOTHING_TO_UPDATE: 'MODULE.NOTHING_TO_UPDATE',
  INVALID_MODULE_KEY: 'MODULE.INVALID_KEY',


  // ========================================
  // ⚙️ ACTION MANAGEMENT
  // ========================================
  ACTION_KEY_REQUIRED: 'ACTION.KEY_REQUIRED',
  ACTION_EXISTS: 'ACTION.EXISTS',
  ACTION_NAME_EXISTS: 'ACTION.NAME_EXISTS',

  ACTION_ADDED: 'ACTION.ADDED',
  ACTION_ADD_FAILED: 'ACTION.ADD_FAILED',

  ACTION_UPDATED: 'ACTION.UPDATED',
  ACTION_UPDATE_FAILED: 'ACTION.UPDATE_FAILED',

  ACTION_DELETED: 'ACTION.DELETED',
  ACTION_DELETE_FAILED: 'ACTION.DELETE_FAILED',

  DUPLICATE_ACTION_KEY: 'ACTION.DUPLICATE_KEY',
  INVALID_ACTION_KEY: 'ACTION.INVALID_KEY',
  ACTIONS_ARRAY_REQUIRED: 'ACTIONS.ARRAY_REQUIRED',

  ACTION_NOT_FOUND: 'ACTION.NOT_FOUND',


  // ========================================
  // 🛡️ ROLE & PERMISSION MANAGEMENT
  // ========================================
  ROLE_NAME_REQUIRED: 'ROLE.NAME_REQUIRED',
  ROLE_EXISTS: 'ROLE.EXISTS',

  ROLE_CREATED: 'ROLE.CREATED',
  ROLE_CREATE_FAILED: 'ROLE.CREATE_FAILED',

  ROLE_LIST_FETCHED: 'ROLE.LIST_FETCHED',
  ROLE_LIST_FAILED: 'ROLE.LIST_FAILED',

  ROLE_NOT_FOUND: 'ROLE.NOT_FOUND',

  ROLE_UPDATED: 'ROLE.UPDATED',
  ROLE_UPDATE_FAILED: 'ROLE.UPDATE_FAILED',

  ROLE_STATUS_REQUIRED: 'ROLE.STATUS_REQUIRED',
  ROLE_STATUS_UPDATED: 'ROLE.STATUS_UPDATED',
  ROLE_STATUS_UPDATE_FAILED: 'ROLE.STATUS_UPDATE_FAILED',

  MODULES_ARRAY_REQUIRED: 'MODULES.ARRAY_REQUIRED',

  CANNOT_MODIFY_SUPER_ADMIN: 'ROLE.CANNOT_MODIFY_SUPER_ADMIN',

  PERMISSIONS_UPDATED: 'PERMISSIONS.UPDATED',
  PERMISSIONS_ASSIGN_FAILED: 'PERMISSIONS.ASSIGN_FAILED',


  // ========================================
  // 🛡️ PLANs MANAGEMENT
  // ========================================

  PLAN_NAME_REQUIRED: 'PLAN.NAME_REQUIRED',
  PLAN_CREATED: 'PLAN.CREATED',
  PLAN_CREATE_FAILED: 'PLAN.CREATE_FAILED',
  PLAN_LIST_FETCHED: 'PLAN.LIST_FETCHED',
  PLAN_LIST_FAILED: 'PLAN.LIST_FAILED',
  PLAN_NOT_FOUND: 'PLAN.NOT_FOUND',
  PLAN_FETCHED: 'PLAN.FETCHED',
  PLAN_FETCH_FAILED: 'PLAN.FETCH_FAILED',
  PLAN_UPDATED: 'PLAN.UPDATED',
  PLAN_UPDATE_FAILED: 'PLAN.UPDATE_FAILED',
  PLAN_DELETED: 'PLAN.DELETED',
  PLAN_DELETE_FAILED: 'PLAN.DELETE_FAILED',

  // ========================================
  // 🛡️ PLANs PERMISSION MANAGEMENT
  // ========================================  
  
  MODULES_ARRAY_REQUIRED: 'PERMISSION.MODULES_ARRAY_REQUIRED',
  MODULES_ASSIGNED: 'PERMISSION.MODULES_ASSIGNED',
  MODULES_ASSIGN_FAILED: 'PERMISSION.MODULES_ASSIGN_FAILED',
  INVALID_MODULE_KEY: 'PERMISSION.INVALID_MODULE_KEY',
  INVALID_ACTION_KEY: 'PERMISSION.INVALID_ACTION_KEY',

  // ========================================
  // 🛡️ AFFILIATE MANAGEMENT
  // ========================================  
  
  AFFILIATE_CREATED: 'AFFILIATE.CREATED',
  AFFILIATE_CREATE_FAILED: 'AFFILIATE.CREATE_FAILED',
  AFFILIATE_FETCHED: 'AFFILIATE.FETCHED',
  AFFILIATE_FETCH_FAILED: 'AFFILIATE.FETCH_FAILED',
  AFFILIATE_UPDATED: 'AFFILIATE.UPDATED',
  AFFILIATE_UPDATE_FAILED: 'AFFILIATE.UPDATE_FAILED',
  AFFILIATE_SOFT_DELETED: 'AFFILIATE.SOFT_DELETED',
  AFFILIATE_DELETE_FAILED: 'AFFILIATE.DELETE_FAILED',
  AFFILIATE_NOT_FOUND: 'AFFILIATE.NOT_FOUND',
  AFFILIATE_LIST_FETCHED: 'AFFILIATE.LIST_FETCHED',
  AFFILIATE_LIST_FETCH_FAILED: 'AFFILIATE.LIST_FETCH_FAILED',
  AFFILIATE_RESTORED: 'AFFILIATE.RESTORED',
  AFFILIATE_RESTORE_FAILED: 'AFFILIATE.RESTORE_FAILED',

  // ========================================
  // 🖥️ SYSTEM & SERVER
  // ========================================
  SERVER_ERROR: 'SERVER.ERROR'

};
